packageExtensions:
  "@backstage/backend-plugin-api@*":
    peerDependencies:
      "@backstage/plugin-scaffolder-backend": "*"
    peerDependenciesMeta:
      "@backstage/plugin-scaffolder-backend":
        optional: true

yarnPath: .yarn/releases/yarn-4.4.1.cjs
