nodeLinker: node-modules

# Network settings
httpTimeout: 60000
networkTimeout: 60000

# Enable global cache for faster installs
enableGlobalCache: true

# Compression
compressionLevel: mixed

# Node version check
nodeVersion: ">=18.0.0"
