# kubernetes/backstage/external-secrets.yaml
# External Secrets Operator configuration for production
# Manages secrets from AWS Secrets Manager / HashiCorp Vault

---
# SecretStore - AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: platform-tools
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: backstage
---
# SecretStore - HashiCorp Vault (Alternative)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: platform-tools
spec:
  provider:
    vault:
      server: "https://vault.yourcompany.com"
      path: "backstage"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "backstage"
          serviceAccountRef:
            name: backstage
---
# ExternalSecret - Backstage Application Secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: platform-tools
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create secrets before deployment
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  
  target:
    name: backstage-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # PostgreSQL
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        
        # Session
        SESSION_SECRET: "{{ .session_secret }}"
        
        # ZITADEL
        ZITADEL_CLIENT_ID: "{{ .zitadel_client_id }}"
        ZITADEL_CLIENT_SECRET: "{{ .zitadel_client_secret }}"
        
        # SAML
        AUTH_SAML_CERT: "{{ .saml_cert }}"
        
        # Azure AD
        AZURE_CLIENT_SECRET: "{{ .azure_client_secret }}"
        
        # AI/LLM
        OPENAI_API_KEY: "{{ .openai_api_key }}"
        
        # GitHub
        GITHUB_CLIENT_SECRET: "{{ .github_client_secret }}"
        GITHUB_WEBHOOK_SECRET: "{{ .github_webhook_secret }}"
        GITHUB_PRIVATE_KEY: "{{ .github_private_key | b64dec }}"
        
        # GitLab
        GITLAB_TOKEN: "{{ .gitlab_token }}"
        
        # VictoriaMetrics
        VICTORIAMETRICS_API_KEY: "{{ .victoriametrics_api_key }}"
        
        # Grafana
        GRAFANA_API_KEY: "{{ .grafana_api_key }}"
        
        # Logging
        LOGGING_API_KEY: "{{ .logging_api_key }}"
  
  dataFrom:
    - extract:
        key: backstage/production
---
# ExternalSecret - Database Certificates
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-db-certs
  namespace: platform-tools
spec:
  refreshInterval: 24h
  
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  
  target:
    name: backstage-db-certs
    creationPolicy: Owner
  
  data:
    - secretKey: ca.crt
      remoteRef:
        key: backstage/database/ca-cert
    
    - secretKey: tls.crt
      remoteRef:
        key: backstage/database/client-cert
    
    - secretKey: tls.key
      remoteRef:
        key: backstage/database/client-key
---
# ExternalSecret - Kubernetes Cluster Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-k8s-credentials
  namespace: platform-tools
spec:
  refreshInterval: 12h
  
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  
  target:
    name: backstage-k8s-credentials
    creationPolicy: Owner
  
  data:
    # EKS Clusters
    - secretKey: eks-us-east-1-ca
      remoteRef:
        key: backstage/kubernetes/eks-us-east-1
        property: ca_data
    
    - secretKey: eks-us-east-1-role-arn
      remoteRef:
        key: backstage/kubernetes/eks-us-east-1
        property: role_arn
    
    - secretKey: eks-eu-west-1-ca
      remoteRef:
        key: backstage/kubernetes/eks-eu-west-1
        property: ca_data
    
    - secretKey: eks-eu-west-1-role-arn
      remoteRef:
        key: backstage/kubernetes/eks-eu-west-1
        property: role_arn
    
    # AKS Clusters
    - secretKey: aks-west-europe-ca
      remoteRef:
        key: backstage/kubernetes/aks-west-europe
        property: ca_data
    
    # GKE Clusters
    - secretKey: gke-us-central1-ca
      remoteRef:
        key: backstage/kubernetes/gke-us-central1
        property: ca_data
    
    # On-premise
    - secretKey: onprem-k8s-ca
      remoteRef:
        key: backstage/kubernetes/onprem
        property: ca_data
    
    - secretKey: onprem-k8s-token
      remoteRef:
        key: backstage/kubernetes/onprem
        property: service_account_token
---
# ServiceAccount - Backstage with IRSA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: platform-tools
  annotations:
    # AWS IRSA annotation for SecretsManager access
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/backstage-secrets-reader
automountServiceAccountToken: true
---
# ConfigMap - Non-Sensitive Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: platform-tools
data:
  # Application URLs
  APP_BASE_URL: "https://backstage.yourcompany.com"
  BACKEND_BASE_URL: "https://backstage.yourcompany.com"
  
  # ZITADEL
  ZITADEL_ISSUER: "https://zitadel.yourcompany.com"
  
  # Database (non-sensitive)
  POSTGRES_HOST: "backstage-postgres.cg1234567890.us-east-1.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "backstage"
  POSTGRES_DB: "backstage"
  
  # VictoriaMetrics
  VICTORIAMETRICS_METRICS_URL: "https://victoriametrics.yourcompany.com"
  VICTORIAMETRICS_LOGS_URL: "https://victorialogs.yourcompany.com"
  
  # Grafana
  GRAFANA_URL: "https://grafana.yourcompany.com"
  
  # Redis
  REDIS_URL: "redis://backstage-redis.platform-tools.svc.cluster.local:6379"
  
  # AWS
  AWS_REGION: "us-east-1"
  
  # TechDocs
  TECHDOCS_S3_BUCKET: "backstage-techdocs-prod"
  
  # Kubernetes Cluster URLs
  EKS_US_EAST_1_URL: "https://ABCD1234.gr7.us-east-1.eks.amazonaws.com"
  EKS_EU_WEST_1_URL: "https://EFGH5678.gr7.eu-west-1.eks.amazonaws.com"
  AKS_WEST_EUROPE_URL: "https://backstage-aks-westeu-12345678.hcp.westeurope.azmk8s.io"
  GKE_US_CENTRAL1_URL: "https://123.456.789.012"
  ONPREM_K8S_URL: "https://k8s.internal.yourcompany.com"
  
  # Azure
  AZURE_TENANT_ID: "12345678-1234-1234-1234-123456789012"
  AZURE_DOMAIN_HINT: "yourcompany.com"
  
  # GitHub
  GITHUB_APP_ID: "123456"
  GITHUB_CLIENT_ID: "Iv1.a1b2c3d4e5f6g7h8"
  
  # Logging
  LOGGING_AGGREGATOR_HOST: "logs.yourcompany.com"
  
  # Chroma Vector Store
  CHROMA_URL: "http://chroma.platform-tools.svc.cluster.local:8000"
