#!/bin/bash
# setup-dev.sh - Automated local development setup
# Idempotent script for initializing Backstage AIOps Platform

set -euo pipefail

# Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

log() { echo -e "${CYAN}▶ $1${NC}"; }
success() { echo -e "${GREEN}✓ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠ $1${NC}"; }
error() { echo -e "${RED}✗ $1${NC}" >&2; exit 1; }

# Check if running in project directory
if [ ! -f "package.json" ]; then
    error "Must be run from project root directory"
fi

log "Starting Cloud-Native AIOps Platform setup..."

# ==========================================
# 1. Check Prerequisites
# ==========================================
log "Checking prerequisites..."

# Docker
if ! command -v docker &> /dev/null; then
    error "Docker is not installed. Install from https://docs.docker.com/get-docker/"
fi

# Docker Compose
if ! docker compose version &> /dev/null; then
    error "Docker Compose is not installed. Install from https://docs.docker.com/compose/install/"
fi

# Node.js
if ! command -v node &> /dev/null; then
    error "Node.js is not installed. Install from https://nodejs.org/"
fi

NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    error "Node.js version 18+ required (current: $NODE_VERSION)"
fi

# Yarn
if ! command -v yarn &> /dev/null; then
    warn "Yarn not found, installing..."
    npm install -g yarn
fi

success "Prerequisites check passed"

# ==========================================
# 2. Install Dependencies
# ==========================================
log "Installing Node.js dependencies..."

# Fix invalid dependency version causing YN0082
log "Fixing package.json dependencies..."
node -e '
  const fs = require("fs");
  const files = ["package.json", "packages/backend/package.json"];
  files.forEach(f => {
    if (fs.existsSync(f)) {
      try {
        let content = fs.readFileSync(f, "utf8");
        // Fix trailing commas from previous sed runs
        content = content.replace(/,(\s*})/g, "$1");
        const pkg = JSON.parse(content);
        if (f.includes("packages/backend/package.json")) {
          pkg.backstage = pkg.backstage || {};
          pkg.backstage.role = "backend";
          if (!pkg.dependencies["@backstage/backend-defaults"]) {
            pkg.dependencies["@backstage/backend-defaults"] = "^0.2.0";
          }
          if (!pkg.dependencies["@backstage/plugin-proxy-backend"]) {
            pkg.dependencies["@backstage/plugin-proxy-backend"] = "^0.4.14";
          }
          if (!pkg.dependencies["@backstage/plugin-kubernetes-backend"]) {
            pkg.dependencies["@backstage/plugin-kubernetes-backend"] = "^0.17.0";
          }
          if (!pkg.dependencies["@backstage/plugin-app-backend"]) {
            pkg.dependencies["@backstage/plugin-app-backend"] = "^0.3.65";
          }
        }
        if (pkg.dependencies) {
          if (pkg.dependencies["@backstage/plugin-permission-backend"] === "^0.8.2") pkg.dependencies["@backstage/plugin-permission-backend"] = "^0.5.0";
          delete pkg.dependencies["app-config"];
          delete pkg.dependencies["winston-audit"];
          delete pkg.dependencies["@backstage/plugin-ldap-auth-backend"];
          delete pkg.dependencies["@backstage/plugin-microsoft-auth-backend"];
          delete pkg.dependencies["@k-phoen/backstage-plugin-grafana"];
          delete pkg.dependencies["@parsable/backstage-plugin-logstream"];
          delete pkg.dependencies["@roadiehq/backstage-plugin-ai-assistant-rag"];
          delete pkg.dependencies["@suxess-it/backstage-plugin-k8sgpt"];
          delete pkg.dependencies["kubernetes-client"];
        }
        fs.writeFileSync(f, JSON.stringify(pkg, null, 2));
      } catch (e) { console.error("Failed to fix " + f, e); }
    }
  });
'

# Fix Yarn PnP ghost dependencies
log "Configuring Yarn package extensions..."
yarn config set 'packageExtensions["@backstage/backend-plugin-api@*"].peerDependencies["@backstage/plugin-scaffolder-backend"]' "*"
yarn config set 'packageExtensions["@backstage/backend-plugin-api@*"].peerDependenciesMeta["@backstage/plugin-scaffolder-backend"].optional' true

YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
success "Dependencies installed"

# ==========================================
# 3. Create Required Directories
# ==========================================
log "Creating required directories..."
mkdir -p catalog/{teams,systems,components}
mkdir -p docs/{architecture,runbooks}
mkdir -p tests/{e2e,load,unit}
mkdir -p packages/{app,backend,cli}
success "Directories created"

# ==========================================
# 4. Generate Environment File
# ==========================================
if [ ! -f ".env" ]; then
    log "Generating .env file..."
    cat > .env << 'EOF'
# Generated by setup-dev.sh
# Customize as needed

# User ID for Docker containers (prevents permission issues)
UID=1000
GID=1000

# Database
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=backstage

# Node environment
NODE_ENV=development
NODE_OPTIONS=--max-old-space-size=4096
EOF
    success ".env file created"
else
    log ".env file already exists (skipping)"
fi

# ==========================================
# 5. Initialize Docker Network
# ==========================================
log "Checking Docker network..."
if ! docker network inspect backstage-network &> /dev/null; then
    docker network create backstage-network
    success "Docker network created"
else
    log "Docker network already exists"
fi

# ==========================================
# 6. Pull Docker Images
# ==========================================
log "Pulling Docker images (this may take a few minutes)..."
docker compose pull --quiet
success "Docker images pulled"

# ==========================================
# 7. Initialize Database
# ==========================================
log "Starting PostgreSQL..."
docker compose up -d postgres

log "Waiting for PostgreSQL to be ready..."
#for i in {1..30}; do
#    if docker compose exec -T postgres pg_isready -U postgres &> /dev/null; then
#        success "PostgreSQL is ready"
#        break
#    fi
#    sleep 2
#    if [ $i -eq 30 ]; then
#        error "PostgreSQL failed to start after 60 seconds"
#    fi
#done

# ==========================================
# 8. Start Remaining Services
# ==========================================
log "Starting VictoriaMetrics..."
docker compose up -d victoriametrics

log "Starting VictoriaLogs..."
docker compose up -d victorialogs

log "Starting Mock Kubernetes API..."
docker compose up -d mock-k8s

# Wait for services
sleep 5

# ==========================================
# 9. Verify Service Health
# ==========================================
log "Verifying service health..."

services=(
    "postgres:5432"
    "victoriametrics:8428/health"
    "victorialogs:9428/health"
    "mock-k8s:8081/healthz"
)

for service in "${services[@]}"; do
    name=$(echo "$service" | cut -d: -f1)
    endpoint=$(echo "$service" | cut -d: -f2-)
    
    if echo "$endpoint" | grep -q "/"; then
        # HTTP endpoint
        url="http://localhost:$endpoint"
        if curl -sf "$url" &> /dev/null; then
            success "$name is healthy"
        else
            warn "$name health check failed (may still be starting)"
        fi
    else
        # TCP port
        port="$endpoint"
        if nc -z localhost "$port" 2>/dev/null; then
            success "$name is reachable"
        else
            warn "$name connection failed (may still be starting)"
        fi
    fi
done

# ==========================================
# 10. Create Sample Catalog Entities
# ==========================================
if [ ! -f "catalog/teams/platform-engineers.yaml" ]; then
    log "Creating sample catalog entities..."
    
    cat > catalog/teams/platform-engineers.yaml << 'EOF'
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineering
  description: Platform Engineering Team
spec:
  type: team
  profile:
    displayName: Platform Engineering
    email: platform@yourcompany.com
  children: []
EOF
    
    cat > catalog/teams/team-a.yaml << 'EOF'
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: Team A
spec:
  type: team
  profile:
    displayName: Team A
    email: team-a@yourcompany.com
  children: []
EOF

    cat > catalog/all.yaml << 'EOF'
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-catalog
  description: Sample catalog entities
spec:
  targets:
    - ./teams/platform-engineers.yaml
    - ./teams/team-a.yaml
EOF

    success "Sample catalog entities created"
else
    log "Catalog entities already exist"
fi

# ==========================================
# 11. Display Summary
# ==========================================
echo ""
echo -e "${GREEN}════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✓ Setup Complete!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}Services:${NC}"
echo "  • PostgreSQL:      http://localhost:5432"
echo "  • VictoriaMetrics: http://localhost:8428"
echo "  • VictoriaLogs:    http://localhost:9428"
echo "  • Mock K8s API:    http://localhost:8081"
echo ""
echo -e "${CYAN}Next Steps:${NC}"
echo "  1. Start Backstage:"
echo "     ${YELLOW}make dev${NC}"
echo ""
echo "  2. Open Backstage UI:"
echo "     ${YELLOW}http://localhost:3000${NC}"
echo ""
echo -e "${CYAN}Useful Commands:${NC}"
echo "  make help          - Show all available commands"
echo "  make logs          - View Backstage logs"
echo "  make clean         - Stop all services"
echo "  make test          - Run tests"
echo ""
echo -e "${GREEN}════════════════════════════════════════════════${NC}"
