apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineering
  description: Platform Engineering Team
spec:
  type: team
  profile:
    displayName: Platform Engineering
    email: platform@yourcompany.com
  children: []
